package com.fitpulse.app.domain.model

import java.time.Instant
import java.time.LocalDate

enum class WorkoutType(val displayName: String, val icon: String, val isGpsTracked: Boolean) {
    WALKING("Walking", "directions_walk", true),
    RUNNING("Running", "directions_run", true),
    CYCLING("Cycling", "directions_bike", true),
    HIKING("Hiking", "hiking", true),
    GYM("Gym Workout", "fitness_center", false),
    TREADMILL("Treadmill", "stairs", false),
    OTHER("Other Workout", "sports", false)
}

enum class GpsStatus(val label: String) {
    READY("GPS Ready"),
    SEARCHING("GPS Searching..."),
    WEAK("GPS Weak"),
    LOST("GPS Lost")
}

data class GpsPoint(
    val latitude: Double,
    val longitude: Double,
    val altitude: Double? = null,
    val speed: Float? = null, // in m/s
    val accuracy: Float? = null,
    val timestamp: Instant = Instant.now()
)

data class HeartRateRecord(
    val bpm: Int,
    val timestamp: Instant,
    val isResting: Boolean = false,
    val source: String = "Health Connect"
)

enum class HeartRateZone(val zoneNumber: Int, val displayName: String, val minBpm: Int, val maxBpm: Int) {
    ZONE_1(1, "Very Light (Warm Up)", 90, 114),
    ZONE_2(2, "Light (Fat Burn)", 115, 133),
    ZONE_3(3, "Moderate (Aerobic)", 134, 152),
    ZONE_4(4, "Hard (Anaerobic)", 153, 171),
    ZONE_5(5, "Maximum (VO2 Max)", 172, 200)
}

enum class SleepStage {
    AWAKE,
    LIGHT,
    DEEP,
    REM
}

data class SleepStageRecord(
    val stage: SleepStage,
    val startTime: Instant,
    val endTime: Instant
)

data class SleepSession(
    val id: String,
    val startTime: Instant,
    val endTime: Instant,
    val durationMinutes: Long,
    val stages: List<SleepStageRecord> = emptyList(),
    val source: String = "Health Connect"
)

data class DailyActivitySummary(
    val date: LocalDate,
    val steps: Long = 0,
    val distanceMeters: Double = 0.0,
    val activeCalories: Double = 0.0,
    val totalCalories: Double = 0.0,
    val restingHeartRate: Int? = null,
    val averageHeartRate: Int? = null,
    val minHeartRate: Int? = null,
    val maxHeartRate: Int? = null,
    val sleepMinutes: Long? = null,
    val waterMilliliters: Int = 0,
    val weightKg: Double? = null,
    val workoutsCount: Int = 0,
    val stepGoal: Long = 10000,
    val waterGoalMl: Int = 2500,
    val sleepGoalMinutes: Long = 480
)

data class UserProfile(
    val id: String = "default_user",
    val name: String = "Athlete",
    val age: Int? = null,
    val gender: String? = null,
    val heightCm: Double? = null,
    val weightKg: Double? = null,
    val activityLevel: String = "MODERATE", // SEDENTARY, LIGHT, MODERATE, VERY_ACTIVE
    val unitSystem: String = "METRIC", // METRIC, IMPERIAL
    val stepGoal: Long = 10000,
    val waterGoalMl: Int = 2500,
    val sleepGoalMinutes: Long = 480,
    val weeklyWorkoutGoal: Int = 4,
    val weightTargetKg: Double? = null,
    val isOnboarded: Boolean = false,
    val developerModeEnabled: Boolean = false
)

data class WorkoutSession(
    val id: String,
    val type: WorkoutType,
    val startTime: Instant,
    val endTime: Instant? = null,
    val durationSeconds: Long = 0,
    val distanceMeters: Double = 0.0,
    val activeCalories: Double = 0.0,
    val averageSpeedKmh: Double = 0.0,
    val maxSpeedKmh: Double = 0.0,
    val averagePaceSecPerKm: Long = 0,
    val elevationGainMeters: Double = 0.0,
    val averageHeartRate: Int? = null,
    val maxHeartRate: Int? = null,
    val points: List<GpsPoint> = emptyList(),
    val notes: String = ""
)

data class AchievementItem(
    val id: String,
    val title: String,
    val description: String,
    val icon: String,
    val unlockedAt: Instant? = null,
    val isUnlocked: Boolean = false,
    val progress: Float = 0f // 0.0 to 1.0
)

data class StreaksData(
    val currentStepStreak: Int = 0,
    val longestStepStreak: Int = 0,
    val currentWorkoutStreak: Int = 0,
    val currentWaterStreak: Int = 0,
    val currentSleepStreak: Int = 0
)

data class HealthScore(
    val score: Int, // 0 - 100
    val activityScore: Int,
    val sleepScore: Int,
    val hydrationScore: Int,
    val workoutScore: Int,
    val recoveryScore: Int,
    val disclaimer: String = "This is a wellness score generated by FitPulse and is not a medical measurement."
)

data class AiFitnessInsight(
    val id: String,
    val title: String,
    val content: String,
    val category: String, // ACTIVITY, RECOVERY, HYDRATION, STREAK
    val timestamp: Instant = Instant.now(),
    val isSupportedByRealData: Boolean = true
)
